### ISSUE TITLE
time.Now().Unix() vs. time.Now().UnixNano()

### ISSUE THREAD

**Issue by fattenap** [lucsky/cuid#1]
Hi,

I noticed at lines https://github.com/lucsky/cuid/blob/master/cuid.go#L27 and https://github.com/lucsky/cuid/blob/master/cuid.go#L58 you used time.Now().Unix(). I've seen in other examples people using time.Now().UnixNano(). Just curious as to why you chose  not to use time.Now().UnixNano()?

Thanks
Frank

**Comment by lucsky** [comment]
(5 years later...)

Very good point. I have changed the code to use `time.Now().UnixNano()` which gives timestamps a better precision (in 488fbe36d105d70fa3590b97cdc9bb1b2c7c0ff7)

Thank you for your, um, patience... 😇
