### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [lucsky/cuid#9]
I found that this project already [supports Go modules](https://github.com/lucsky/cuid/blob/master/go.mod). The latest version v1.2 committed on 29 Oct 2019, the last version which followed [Semantic Versioning](https://semver.org) is v1.0.2, committed on 25 Aug 2018. If module user run "go get github.com/lucsky/cuid", the old version v1.0.2 will be required.
```
$go get github.com/lucsky/cuid
go: downloading github.com/lucsky/cuid v1.0.2
go: github.com/lucsky/cuid upgrade => v1.0.2
```

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@mpsdantas  @maitesin  Could you help me review this issue? Thx :p

**Comment by erutherford** [comment]
If we could get an updated `v1.1.0` tag that'd be great, as the tag is currently formatted you can't target it with go modules.

**Comment by Jeyanthinath** [comment]
Same issue here, can't use slug with the current version supported by go.mod.

**Comment by erutherford** [comment]
@lucsky is there any way we could get a `v1.1.0` tag created and commit to start using semver going forward? I greatly appreciate your work on this library and it'd be great if we could easily use this with go modules.

**Comment by lucsky** [comment]
@erutherford and @Jeyanthinath: I'm sorry this has been lagging for so long, I will take care of this before the end of the week. Feel free to vigorously poke me if I don't 😉

**Comment by erutherford** [comment]
Fantastic, thank you.

**Comment by lucsky** [comment]
Alright, I have integrated a couple changes and tagged version 1.2 (`v1.2.0`). I have also added semantically correct tags for v1 et v1.1.

Again, I apologize for the insane delay.
